### PR TITLE
Remove obsolete guard agains division by zero

### PR DESCRIPTION
**Pull request by daschuer**
This fixes https://github.com/mixxxdj/mixxx/issues/10764

### CODE REVIEW

**Comment by daschuer** [comment]
All thanks to @nm2107 for pointing out the correct fix

**Comment by Swiftb0y** [comment]
why did you file this against your fork?

**Comment by daschuer** [comment]
GitHub must have tricked me.

**Comment by daschuer** [comment]
Replaced by https://github.com/mixxxdj/mixxx/pull/11977

**Pull request closed without merging**
