### PR TITLE
CMake: always set CMAKE_OSX_DEPLOYMENT_TARGET=10.12

### PR DESCRIPTION
**Pull request by Be-ing**
It seems that CMake sets this to a default value, so checking
if it is already set does not work.

### CODE REVIEW

**Comment by Be-ing** [comment]
https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html

> If not set explicitly the value is initialized by the MACOSX_DEPLOYMENT_TARGET environment variable, if set, and *otherwise computed based on the host platform*.

**Review by daschuer — CHANGES_REQUESTED** [review]
This still uses: 
CMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.15

**Comment by daschuer** [comment]
You need to move the before project()

```
The value of this variable should be set prior to the first project() or enable_language()
```

**Comment by Be-ing** [comment]
Now it is actually setting CMAKE_OSX_DEPLOYMENT_TARGET.

**Comment by daschuer** [comment]
You may remove the last commit or add windows update as well. 
We need to update the environment later anyway, so this commit can be IMHO removed.

**Comment by Be-ing** [comment]
I don't think we should wait to update the build environments because that would break CMAKE_BUILD_TYPE=Debug (which is the default) on macOS.

**Comment by Be-ing** [comment]
CMAKE_OSX_DEPLOYMENT_TARGET is not getting passed down to the libdjinterop build:

```
[807/868] Linking CXX executable mixxx
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(enginelibrary.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(crate.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(track.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(database.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(crate_impl.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(database_impl.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(el_storage.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(el_database_impl.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(schema.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(track_impl.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(util.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(performance_data_format.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(el_track_impl.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(el_crate_impl.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(el_transaction_guard_impl.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(transaction_guard.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(schema_1_6_0.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(schema_1_7_1.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(schema_1_9_1.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(schema_1_11_1.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(schema_1_13_0.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(schema_1_13_1.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(schema_1_13_2.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(schema_1_15_0.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(schema_1_17_0.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(schema_1_18_0_ep.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(schema_1_18_0_fw.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(encode_decode_utils.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: object file (lib/libdjinterop-install/lib/libdjinterop.a(transaction_guard_impl.cpp.o)) was built for newer macOS version (11.0) than being linked (10.12)
ld: warning: could not create compact unwind for _ff_cfhd_init_vlcs: stack subq instruction is too different from dwarf stack size
ld: warning: could not create compact unwind for _ff_rl_init_vlc: stack subq instruction is too different from dwarf stack size
```

We should fix this by adding libdjinterop to the vcpkg environment.

**Comment by Be-ing** [comment]
Upstream PR to update libdjinterop: https://github.com/microsoft/vcpkg/pull/20136

**Comment by Be-ing** [comment]
This is really nice that we can now use the same tool to maintain both Windows and macOS dependencies. :)

**Review by daschuer — APPROVED** [review]
LGTM, thank you

**Pull request merged**
