### PR TITLE
Hotfix for SIGSEGV

### PR DESCRIPTION
**Pull request by uklotzde**

### CODE REVIEW

**Comment by nopeppermint** [comment]
I rebuild branch daschuer:jmigual-library-redesign with this hotfix and there are no longer crashed when creating new crate in the first minutes you're running mixxx on Linux

**Comment by jmigual** [comment]
Why wasn't this merged? It still crashes in daschuer:jmigual-library-redesign

**Comment by daschuer** [comment]
I guess this was superseded by another PR. .. ?

**Comment by daschuer** [comment]
It still crashes, without this patch even after merge with master. 
I think it is save to merge this. Thank you @uklotzde for the work.

**Pull request merged**
