### PR TITLE
QAtomicInt + Debug Assertions

### PR DESCRIPTION
**Pull request by uklotzde**
This could be a solution, Travis build is running:
https://travis-ci.org/uklotzde/mixxx/builds/592829270

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you. I did a similar trick in the target branch. Now it is conflicting.
Can you resolve the conflicts?

**Comment by daschuer** [comment]
Oh, hold on, I am working in a proposal for the idle state assertions.

**Comment by uklotzde** [comment]
Next try: https://travis-ci.org/uklotzde/mixxx/builds/592937461

This is just a proposal on how to fix the state conflicts by explicitly handling the unloading of tracks.

**Comment by uklotzde** [comment]
And we need the check in newTrack() into an undefined state.

**Pull request merged**
