### PR TITLE
Disable broken tests and skip ANGLE DLL install on Windows

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by Swiftb0y** [comment]
If we're not shipping ANGLE on windows, can we rely on the graphics driver to provide a capable openGL implementation? I only found this (quite outdated) page from nvidia https://developer.nvidia.com/opengl-driver

**Comment by Holzhaus** [comment]
I suppose we have to rely on what is installed. From the Qt docs: https://doc.qt.io/qt-6/opengl-changes-qt6.html#removal-of-angle

> ## Removal of ANGLE
>
> On Windows, ANGLE, a third-party OpenGL ES to Direct 3D translator, is no longer included in Qt 6. This means `Qt::AA_UseOpenGLES` and the environment variable `QT_OPENGL=angle` no longer has any effect. In dynamic OpenGL builds there is no automatic fallback to ANGLE in case OpenGL-proper fails to initialize. For [QWindow](https://doc.qt.io/qt-6/qwindow.html) or [QWidget](https://doc.qt.io/qt-6/qwidget.html) based applications using OpenGL directly, for example via [QOpenGLWidget](https://doc.qt.io/qt-6/qopenglwidget.html), this means that OpenGL-proper is the only option at runtime. However, the use of a pure software OpenGL implementation, such as Mesa llvmpipe that is shipped with the pre-built Qt packages, is still available.
>
> For Qt Quick and Qt Quick 3D applications, Qt 6 introduces support for Direct 3D 11, Vulkan, and Metal, in addition to OpenGL. On Windows, Qt 6 defaults to Direct 3D, therefore the effect of the removal of ANGLE is lessened by the addition of support to other graphics APIs.

I also found this outdated page: https://www.khronos.org/opengl/wiki/Getting_Started#Windows

**Comment by daschuer** [comment]
We have a related regression issue with ANGLE https://github.com/mixxxdj/mixxx/issues/11641 that formal blocks the 2.4 release. 
Does this add any take-aways for this?

**Review by daschuer — APPROVED** [review]
All Green, thank you for taking care.

**Pull request merged**
