### PR TITLE
LateNight: fix changes after merging master

### PR DESCRIPTION
**Pull request by ronso0**
fixes a few issues with 1-state button icons in Aux / Mic and rate control section

### CODE REVIEW

**Comment by daschuer** [comment]
This improves the situation a bit. 
But the Aux + Icons are now red and do nothing anymore. 
In Shade all buttons are gone.
Should I merge this anyway?

**Comment by ronso0** [comment]
oooha. don't merge yet, I'll fix lateNight and have al look at the other skins later today.

**Comment by ronso0** [comment]
meeh... I didn't pull beforehand

**Comment by ronso0** [comment]
accidentially closed this,and now I can't reopen it. weird..

**Comment by ronso0** [comment]
actually your branch fine, seems I messed up something locally

**Pull request closed without merging**
