### PR TITLE
Fix some coding issues 

### PR DESCRIPTION
**Pull request by jmigual**
Fix some (not all) coding issues pointed by @timrae. I've fixed the `parented_ptr` issue too.

### CODE REVIEW

**Comment by jmigual** [comment]
Oh I found an issue related to the `parented_ptr` class, some classes have the `parent()` member private and it gives a compilation error. In this case we should force a `u` to `QObject` casting and then `parented_ptr` should be only used with Qt Objects.

See: 
https://travis-ci.org/jmigual/mixxx/jobs/205123907

**Comment by timrae** [comment]
Yes, good idea, that sounds safer anyway! Actually we can probably remove
most of the template code in this case, right?

**Comment by daschuer** [comment]
> Actually we can probably remove most of the template code in this case, right?

If we remove the template nature of parented_ptr, we loose the type safety, having an suspicious up cast on every dereferencing access. 

I think it is more save to check if the pointer actually points to a QObject inherited class. 
std::is_base_of might be uses to verify it. 

I do not understand why parent() is private for some classes. 
In case of SavedQueriesTableModel it should be public, need to investigate this more.

**Comment by jmigual** [comment]
I've tried doing the casting to `QObject` but this prevents us from using `parented_ptr` for `TreeItem` since it does not inherit `QObject` so checking for `QObject` inheritance through `std::is_bas_of` might be a good idea.

**Comment by timrae** [comment]
@jmigual 
Which classes have private parent() functions and why?

**Comment by jmigual** [comment]
> Which classes have private parent() functions and why?

`QAbstractTableModel` has the `QModelIndex parent(const QModelIndex &child) const;` member and it seems that the compiler gets confused, it's really strange.

Now I've tried compiling with Qt5.7 and Qt5.5 and it does not give a compilation error.

-----

By the way I found another issue, if you construct a `nullptr` `parented_ptr` it gives a segmentation fault related to this line:
```c++
explicit parented_ptr(T* t) : m_pObject(t) {
        DEBUG_ASSERT(t->parent() != nullptr);
}
````

We should check if `t == nullptr` before doing the assert.

**Comment by jmigual** [comment]
Ok, it's finally fixed the `parent()` issue with Qt4.8. So this should be ready for merge and I'll add more code fixes later. 

I had to modify the `parented_ptr` class by adding the `nullptr` comparison with `parented_ptr` and adding `nullptr` checking before doing the assert.

**Comment by daschuer** [comment]
LGTM! Thank you.

**Pull request merged**
