### PR TITLE
LateNight / Tango: collapse unconfigured Mic/Aux units, add Setup button

### PR DESCRIPTION
**Pull request by ronso0**

### CODE REVIEW

**Comment by daschuer** [comment]
I think there should be a [+] instead of play in the unconfigured Aux decks. 
When all Aux decks are all unconfigure they are moved up a bit, do not align with the mix regions any more.

**Comment by ronso0** [comment]
You're right. I fixed conflicts and didn't test properly afterwards.
Fixed.

**Comment by ronso0** [comment]
done.

**Comment by daschuer** [comment]
Thank you, LGTM.

**Pull request merged**
